version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Or whichever Python version you need
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt  # Ensure flake8 is in your requirements
      - run:
          name: Run Flake8
          command: flake8 .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

